###### GENERAL PARAMS ######
debug: false
device: "cuda:0"

###### TRAINING PARAMS ######
seed: 1234
batch_size: 8
num_epochs: 300
lr : 0.00001

###### DATASET PARAMS ######
split_file: "./data/splits/real_70.csv"
image_dir: "./data/real/images"
mask_dir: "./data/real/masks"
bbox_dir: "./data/real/bbox"
sdf_dir: "./data/real/sdf_map"
class_map_dir: "./data/real/class_map"
n_subset: 80000000000   # use subset of dataset
image_width: 352       
image_height: 128      
num_classes: 6          # number of classes

###### LOGGING + CHECKPOINTING ######
n_viz_images: 8         # number of images to visualize in log
log_samples_every: 10   # epochs
save_model_every: 5     # epochs

###### PIPELINE ######
pretrained_model: null
save_dir: "./checkpoints/paper/layout_diffusion"

train_scheduler_config: >
  {
      "_class_name": "DDPMScheduler",
      "_diffusers_version": "0.31.0",
      "beta_end": 0.02,
      "beta_schedule": "linear",
      "beta_start": 0.0001,
      "clip_sample": true,
      "clip_sample_range": 1.0,
      "dynamic_thresholding_ratio": 0.995,
      "num_train_timesteps": 1000,
      "prediction_type": "epsilon",
      "rescale_betas_zero_snr": false,
      "sample_max_value": 1.0,
      "steps_offset": 0,
      "thresholding": false,
      "timestep_spacing": "leading",
      "trained_betas": null,
      "variance_type": "fixed_small"
  }

sampling_scheduler_config: >
  {
      "_class_name": "DDPMScheduler",
      "_diffusers_version": "0.31.0",
      "beta_end": 0.02,
      "beta_schedule": "linear",
      "beta_start": 0.0001,
      "clip_sample": true,
      "clip_sample_range": 1.0,
      "dynamic_thresholding_ratio": 0.995,
      "num_train_timesteps": 1000,
      "prediction_type": "epsilon",
      "rescale_betas_zero_snr": false,
      "sample_max_value": 1.0,
      "steps_offset": 0,
      "thresholding": false,
      "timestep_spacing": "leading",
      "trained_betas": null,
      "variance_type": "fixed_small"
  }

network_config: >
  {
    "in_channels": 6,
    "out_channels": 6,
    "image_size": [128, 352],
    "model_channels": 128,
    "num_res_blocks": 2,
    "attention_ds": [32, 16, 8],
    "encoder_channels": 128,
    "dropout": 0.0,
    "channel_mult": [1, 1, 2, 2, 4, 4],
    "use_checkpoint": false,
    "num_heads": -1,
    "num_head_channels": 32,
    "num_heads_upsample": -1,
    "use_scale_shift_norm": true,
    "resblock_updown": true,
    "use_positional_embedding_for_attention": true,
    "num_attention_blocks": 1,
    "layout_encoder": {
      "layout_length": 20,
      "hidden_dim": 128,
      "output_dim": 512,
      "num_layers": 4,
      "num_heads": 8,
      "use_final_ln": true,
      "num_classes_for_layout_object": 7,
      "mask_size_for_layout_object": 32,
      "used_condition_types": ["obj_class", "obj_bbox"],
      "use_positional_embedding": false,
      "resolution_to_attention": [[16,44], [8,22], [4,11]],
      "use_key_padding_mask": false
    }
  }
